device: add e104_bt5040u support
google/OpenSK pull request #607
Opened 2023-03-29 09:45 UTC by wolfyzhang-github

Fixes #545 

- [*] Tests pass
- [*] Appropriate changes to README are included in PR

2023-03-29 12:42 UTC, ia0 requested changes
Thanks for your contribution! This overall looks good to me. I've left some comments for the parts I think must be addressed before merging. I'll also ask a review from @kaczmarczyck next week for coherence with the overall project.

2023-03-29 12:42 UTC, ia0 commented on README.md
> +*	[Ebyte E104-BT5040U](https://ebyte.com/en/product-view-news.html?id=1185)
For consistency with the existing list items:

```suggestion
*   [Ebyte E104-BT5040U](https://ebyte.com/en/product-view-news.html?id=1185)
```

2023-03-29 12:42 UTC, ia0 commented on docs/boards/e104_bt5040u.md
> +In fact, this hardware is a cheaper implementation of the [Nordic nRF52840 Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle), and the vast majority of its circui
nit: Why start with "In fact"?

2023-03-29 12:42 UTC, ia0 commented on docs/boards/e104_bt5040u.md
> +In fact, this hardware is a cheaper implementation of the [Nordic nRF52840 Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle), and the vast majority of its circui
Do you have references why it's cheaper? Otherwise I would omit this first sentence and just keep the part regarding its similarity with the Nordic dongle simplifying the setup.

2023-03-29 12:42 UTC, ia0 commented on docs/boards/e104_bt5040u.md
> +In fact, this hardware is a cheaper implementation of the [Nordic nRF52840 Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle), and the vast majority of its circui
typo: "the , so" seems to be missing a word

2023-03-29 12:42 UTC, ia0 commented on docs/boards/e104_bt5040u.md
> +In fact, the DFU of the E104's nrf52840 chip is corrupted due to a factory firmware issue. You can try to reflash into [an available DFU bootloader](https://github.com/google/OpenSK/issues/545#issuec
nit: Why start with "In fact"?

2023-03-29 12:42 UTC, ia0 commented on docs/boards/e104_bt5040u.md
General comment on markdown, we wrap lines explicitly in the source and don't rely on automatic wrapping from source editors. (This is independent of markdown rendering which ignores source line wrapping when deciding what constitutes a paragraph.)

2023-03-29 12:42 UTC, ia0 commented on docs/boards/e104_bt5040u.md
> +The script will ask you to switch to DFU mode. To activate that on your dongle, keep the button pressed while inserting the device into your USB port. You may additionally need to press the tiny, sid
Instead of copy/pasting all of this from the dongle documentation, I would point to that documentation instead to avoid instructions duplication decreasing maintainability.

2023-03-29 12:42 UTC, ia0 commented on docs/img/e104_front.jpg
Is this ok to use this image? Or should we render it directly from its source instead of copying it in the repository?

@jmichelp Do you know?

2023-04-03 15:43 UTC, kaczmarczyck commented
Thanks! I'm happy to have more documentation about hardware options!

I agree we shouldn't copy as much, and rather point to the Dongle while highlighting the differences:

- DFU problems
- Missing button

Feel free to to copy out of my earlier comments.

2023-12-18 11:36 UTC, kaczmarczyck commented
Closed for inactivity. Feel free to reopen when you decide to address our comments.

2023-12-18 11:36 UTC, closed without merging